---

apiVersion: v1
kind: Service
metadata:
  name: "vault"
spec:
  ports:
    - name: "api"
      port: 8200
    - name: "rpc"
      port: 8201
  clusterIP: None
  selector:
    app: vault
    role: server

---

# On Kubernetes expose Vault to user via a NodePort
apiVersion: v1
kind: Service
metadata:
  name: "vault-ui"
spec:
  type: NodePort
  ports:
    - name: "ui"
      port: 8200
      protocol: TCP
  selector:
    app: vault
    role: server

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
    role: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
      role: server
  template:
    metadata:
      labels:
        app: vault
        role: server
    spec:
      containers:
      - name: vault
        image: vault
        securityContext:
          capabilities:
            add: [ "IPC_LOCK" ]
        env:
          - name: VAULT_DEV_ROOT_TOKEN_ID
            value: "root_token"
        args: [ "server", "-dev" ]
        livenessProbe:
          exec:
            command:
            - pidof
            - vault
          initialDelaySeconds: 5
          timeoutSeconds: 2
        ports:
        - containerPort: 8200
          name: api
